/* ============================================================
   Gyroid — triply periodic minimal surface (TPMS), generated by
   Marching Cubes over the implicit field:

     f(x,y,z) = sin(X)cos(Y) + sin(Y)cos(Z) + sin(Z)cos(X)

   where X = 2π·x / period, etc. The isosurface f = iso is the
   gyroid sheet. period = cell size; `iso` shifts the surface to
   create a thicker / thinner solid fraction (rough density knob).

   Output is a triangle soup (Float32Array) clipped to the model
   interior, suitable for both rendering and contour slicing.
   ============================================================ */

import { edgeTable, triTable } from "./marchingCubesTables.js";

// 8 cube corners, in the standard Marching Cubes ordering.
const CORNERS = [
  [0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0],
  [0, 0, 1], [1, 0, 1], [1, 1, 1], [0, 1, 1],
];
// 12 cube edges, each connecting two corner indices.
const EDGES = [
  [0, 1], [1, 2], [2, 3], [3, 0],
  [4, 5], [5, 6], [6, 7], [7, 4],
  [0, 4], [1, 5], [2, 6], [3, 7],
];

/**
 * Sheet gyroid (TPMS minimal surface):
 *   f = sin(kx+px)cos(ky+py) + sin(ky+py)cos(kz+pz) + sin(kz+pz)cos(kx+px) = iso
 * @param {object} bounds   from computeBounds()
 * @param {MeshSampler} sampler  for clipping to the model interior
 * @param {object} params   gyroidPeriod|cellSize, isoOffset, phaseX/Y/Z
 * @returns {Float32Array} triangle-soup positions
 */
export function generateGyroid(bounds, sampler, params) {
  const fin = (v, d) => (Number.isFinite(v) ? v : d);
  const period = Math.max(2, fin(params.gyroidPeriod, fin(params.cellSize, 12)));
  const k = (2 * Math.PI) / period;
  // Iso-value offset: 0 = symmetric minimal surface; ± shifts the surface so
  // one interlocking channel grows larger than the other (asymmetric softness).
  const iso = Math.max(-0.9, Math.min(0.9, fin(params.isoOffset, 0)));
  // Per-axis phase shift (degrees -> radians) for diagonal orientation.
  const dr = Math.PI / 180;
  const px = fin(params.phaseX, 0) * dr;
  const py = fin(params.phaseY, 0) * dr;
  const pz = fin(params.phaseZ, 0) * dr;

  // Resolution: a fixed number of samples per cell, capped so big
  // models stay responsive.
  const perCell = 6;
  const step0 = period / perCell;
  const pad = step0; // pad one step so the surface closes at the border

  const ox = bounds.min[0] - pad, oy = bounds.min[1] - pad, oz = bounds.min[2] - pad;
  let nx = Math.ceil((bounds.size[0] + 2 * pad) / step0);
  let ny = Math.ceil((bounds.size[1] + 2 * pad) / step0);
  let nz = Math.ceil((bounds.size[2] + 2 * pad) / step0);

  // Cap total sample points (~2.5M) to avoid freezing the tab.
  const MAX = 140;
  const scale = Math.max(nx, ny, nz) > MAX ? MAX / Math.max(nx, ny, nz) : 1;
  nx = Math.max(2, Math.floor(nx * scale));
  ny = Math.max(2, Math.floor(ny * scale));
  nz = Math.max(2, Math.floor(nz * scale));
  const sx = (bounds.size[0] + 2 * pad) / nx;
  const sy = (bounds.size[1] + 2 * pad) / ny;
  const sz = (bounds.size[2] + 2 * pad) / nz;

  const field = (x, y, z) => {
    const ax = k * x + px, ay = k * y + py, az = k * z + pz;
    return Math.sin(ax) * Math.cos(ay) +
           Math.sin(ay) * Math.cos(az) +
           Math.sin(az) * Math.cos(ax) - iso;
  };

  const out = [];
  const val = new Float64Array(8);
  const pos = new Array(8);

  for (let iz = 0; iz < nz; iz++) {
    for (let iy = 0; iy < ny; iy++) {
      for (let ix = 0; ix < nx; ix++) {
        // Evaluate the field at the 8 corners of this cube.
        let cubeIndex = 0;
        for (let c = 0; c < 8; c++) {
          const cx = ox + (ix + CORNERS[c][0]) * sx;
          const cy = oy + (iy + CORNERS[c][1]) * sy;
          const cz = oz + (iz + CORNERS[c][2]) * sz;
          pos[c] = [cx, cy, cz];
          const f = field(cx, cy, cz);
          val[c] = f;
          if (f < 0) cubeIndex |= (1 << c);
        }

        const edges = edgeTable[cubeIndex];
        if (edges === 0) continue;

        // Interpolate a vertex on each crossed edge.
        const vlist = new Array(12);
        for (let e = 0; e < 12; e++) {
          if (edges & (1 << e)) {
            const [a, b] = EDGES[e];
            const t = val[a] / (val[a] - val[b]);
            vlist[e] = [
              pos[a][0] + t * (pos[b][0] - pos[a][0]),
              pos[a][1] + t * (pos[b][1] - pos[a][1]),
              pos[a][2] + t * (pos[b][2] - pos[a][2]),
            ];
          }
        }

        // Emit triangles, keeping only those whose centroid lies
        // inside the imported model (clips the gyroid to the part).
        const tri = triTable[cubeIndex];
        for (let i = 0; i < tri.length; i += 3) {
          const p0 = vlist[tri[i]], p1 = vlist[tri[i + 1]], p2 = vlist[tri[i + 2]];
          const mx = (p0[0] + p1[0] + p2[0]) / 3;
          const my = (p0[1] + p1[1] + p2[1]) / 3;
          const mz = (p0[2] + p1[2] + p2[2]) / 3;
          if (!sampler.isInside(mx, my, mz)) continue;
          out.push(p0[0], p0[1], p0[2], p1[0], p1[1], p1[2], p2[0], p2[1], p2[2]);
        }
      }
    }
  }
  return new Float32Array(out);
}
